### ISSUE TITLE
原表中删除或者更新数据，搜索会直接崩溃

### ISSUE THREAD

**Issue by EnjoyWT** [pipi32167/SQLiteSwiftDemo#1]
作者你好，demo 中测试，原表删除一条数据后，重新搜索，会报以下错误。
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: database disk image is malformed (code: 11)
请问，你有遇到吗？ 原表删除，操作后还要做其他操作不？

**Comment by EnjoyWT** [comment]
放弃自动触发了，修改成如下，可以看原文档。
https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#full-text-search
手动触发
![WeChat1090293e0ab7bc55526de754b92da4f5](https://github.com/pipi32167/SQLiteSwiftDemo/assets/17864126/3cec98a3-dbd1-4e15-a0b2-5a86e6ffabcd)

**Comment by pipi32167** [comment]
我查了一下似乎是数据库文件损坏了，是必然出现的问题吗？

**Comment by EnjoyWT** [comment]
是的，必现。用sqlite.swift 库手动同步数据吧，测试是可以用的。至于为啥崩溃，没有找到原因。如果你找到了，告诉一声。
